name: 🏷️ ProQuo
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
permissions:
  contents: read
  pull-requests: read
jobs:
  price:
    name: Review Price Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: proquo-result
          path: proquo-result.json
